/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.ControladorDescarte;

import java.util.ArrayList;
import java.util.Objects;

/**
 *
 * @author ciro_
 */
public class VistaDescarte extends javax.swing.JFrame implements VerCartas,Observer{

    /**
     * Creates new form VistaDescarte
     */
    private ControladorDescarte controlador;
    private ArrayList<String> jugadores;
    public void agregarseAMironesEventos(){
        controlador.agregarMironEventos(this);
    }
    public void setControlador(ControladorDescarte controlador) {
        this.controlador = controlador;
        controlador.agregarVerCartas(this);

    }

    public void setImagenes(ArrayList<String> direcciones) {

        imgCarta1.setIcon(new javax.swing.ImageIcon(direcciones.get(0)));
        imgCarta2.setIcon(new javax.swing.ImageIcon(direcciones.get(1)));
        imgCarta3.setIcon(new javax.swing.ImageIcon(direcciones.get(2)));
        imgCarta4.setIcon(new javax.swing.ImageIcon(direcciones.get(3)));
        imgCarta5.setIcon(new javax.swing.ImageIcon(direcciones.get(4)));
    }

    public VistaDescarte() {
        initComponents();
    }
    @Override
    public void actualizarCartas(ArrayList<String> mensaje) {
        setImagenes(mensaje);

    }

    @Override
    public void actualizarJugada(String jugada) {

    }

    @Override
    public void update(String str) {

    }

    @Override
    public void updateApuestaMin(int i) {

    }

    @Override
    public void updateApuestaInicial(int i) {

    }

    @Override
    public void updateMontoBote(int i) {

    }

    @Override
    public void updateTurnoActual(String nombre) {
        nombreJugador.setText(controlador.nombreJugador());
        if (Objects.equals(nombre, controlador.nombreJugador())){
            turno.setText("TU TURNO");
        }
        else turno.setText("TURNO: "+nombre);
    }

    @Override
    public void updateJugadores(ArrayList<String> nombres) {
       jugadores=nombres;
    }

    @Override
    public void updateEtapa(boolean etapaDescarte) {
        if (jugadores.contains(controlador.nombreJugador())){
            nombreJugador.setText(controlador.nombreJugador());
            this.setVisible(etapaDescarte);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        carta1 = new javax.swing.JPanel();
        imgCarta1 = new javax.swing.JLabel();
        carta2 = new javax.swing.JPanel();
        imgCarta2 = new javax.swing.JLabel();
        carta3 = new javax.swing.JPanel();
        imgCarta3 = new javax.swing.JLabel();
        carta4 = new javax.swing.JPanel();
        imgCarta4 = new javax.swing.JLabel();
        carta5 = new javax.swing.JPanel();
        imgCarta5 = new javax.swing.JLabel();
        descarteCarta1 = new javax.swing.JCheckBox();
        descarteCarta2 = new javax.swing.JCheckBox();
        descarteCarta3 = new javax.swing.JCheckBox();
        descarteCarta4 = new javax.swing.JCheckBox();
        descarteCarta5 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonFinalizar = new javax.swing.JButton();
        turno = new javax.swing.JLabel();
        nombreJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(8, 77, 6));

        jPanel4.setBackground(new java.awt.Color(9, 68, 7));

        imgCarta1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ciro_\\OneDrive\\Escritorio\\mavenproject1\\src\\main\\java\\Images\\Atras.png")); // NOI18N

        javax.swing.GroupLayout carta1Layout = new javax.swing.GroupLayout(carta1);
        carta1.setLayout(carta1Layout);
        carta1Layout.setHorizontalGroup(
                carta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carta1Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(imgCarta1)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        carta1Layout.setVerticalGroup(
                carta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imgCarta1)
        );

        imgCarta2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ciro_\\OneDrive\\Escritorio\\mavenproject1\\src\\main\\java\\Images\\Atras.png")); // NOI18N

        javax.swing.GroupLayout carta2Layout = new javax.swing.GroupLayout(carta2);
        carta2.setLayout(carta2Layout);
        carta2Layout.setHorizontalGroup(
                carta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(imgCarta2)
                                .addGap(0, 0, 0))
        );
        carta2Layout.setVerticalGroup(
                carta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imgCarta2)
        );

        imgCarta3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ciro_\\OneDrive\\Escritorio\\mavenproject1\\src\\main\\java\\Images\\Atras.png")); // NOI18N

        javax.swing.GroupLayout carta3Layout = new javax.swing.GroupLayout(carta3);
        carta3.setLayout(carta3Layout);
        carta3Layout.setHorizontalGroup(
                carta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carta3Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(imgCarta3)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        carta3Layout.setVerticalGroup(
                carta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carta3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(imgCarta3))
        );

        carta4.setToolTipText("");

        imgCarta4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ciro_\\OneDrive\\Escritorio\\mavenproject1\\src\\main\\java\\Images\\Atras.png")); // NOI18N

        javax.swing.GroupLayout carta4Layout = new javax.swing.GroupLayout(carta4);
        carta4.setLayout(carta4Layout);
        carta4Layout.setHorizontalGroup(
                carta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carta4Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(imgCarta4)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        carta4Layout.setVerticalGroup(
                carta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carta4Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(imgCarta4)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        imgCarta5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ciro_\\OneDrive\\Escritorio\\mavenproject1\\src\\main\\java\\Images\\Atras.png")); // NOI18N

        javax.swing.GroupLayout carta5Layout = new javax.swing.GroupLayout(carta5);
        carta5.setLayout(carta5Layout);
        carta5Layout.setHorizontalGroup(
                carta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carta5Layout.createSequentialGroup()
                                .addComponent(imgCarta5)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        carta5Layout.setVerticalGroup(
                carta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carta5Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(imgCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        descarteCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descarteCarta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(carta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descarteCarta1)
                                .addGap(95, 95, 95)
                                .addComponent(descarteCarta2)
                                .addGap(95, 95, 95)
                                .addComponent(descarteCarta3)
                                .addGap(95, 95, 95)
                                .addComponent(descarteCarta4)
                                .addGap(95, 95, 95)
                                .addComponent(descarteCarta5)
                                .addGap(104, 104, 104))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(carta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(carta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(carta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(carta2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(carta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(descarteCarta1)
                                        .addComponent(descarteCarta2)
                                        .addComponent(descarteCarta3)
                                        .addComponent(descarteCarta4)
                                        .addComponent(descarteCarta5))
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(9, 68, 7));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESCARTE");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ciro_\\OneDrive\\Escritorio\\mavenproject1\\src\\main\\java\\Images\\R.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel1))
                        .addComponent(jLabel2)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ciro_\\OneDrive\\Escritorio\\mavenproject1\\src\\main\\java\\Images\\R.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        botonFinalizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonFinalizar.setText("Finalizar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        turno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        turno.setForeground(new java.awt.Color(255, 255, 255));
        turno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turno.setText("jLabel4");

        nombreJugador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        nombreJugador.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(264, 264, 264))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void descarteCarta1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<Integer> cartasSeleccionadas=new ArrayList<>();
        if(descarteCarta1.isSelected()){
            cartasSeleccionadas.add(1);
        }
        else cartasSeleccionadas.add(0);
        if(descarteCarta2.isSelected()){
            cartasSeleccionadas.add(1);
        }
        else cartasSeleccionadas.add(0);
        if(descarteCarta3.isSelected()){
            cartasSeleccionadas.add(1);
        }
        else cartasSeleccionadas.add(0);
        if(descarteCarta4.isSelected()){
            cartasSeleccionadas.add(1);
        }
        else cartasSeleccionadas.add(0);
        if(descarteCarta5.isSelected()){
            cartasSeleccionadas.add(1);
        }
        else cartasSeleccionadas.add(0);
        controlador.recibirDescartes(cartasSeleccionadas);
        descarteCarta1.setSelected(false);
        descarteCarta2.setSelected(false);
        descarteCarta3.setSelected(false);
        descarteCarta4.setSelected(false);
        descarteCarta5.setSelected(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDescarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDescarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDescarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDescarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDescarte().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JPanel carta1;
    private javax.swing.JPanel carta2;
    private javax.swing.JPanel carta3;
    private javax.swing.JPanel carta4;
    private javax.swing.JPanel carta5;
    private javax.swing.JCheckBox descarteCarta1;
    private javax.swing.JCheckBox descarteCarta2;
    private javax.swing.JCheckBox descarteCarta3;
    private javax.swing.JCheckBox descarteCarta4;
    private javax.swing.JCheckBox descarteCarta5;
    private javax.swing.JLabel imgCarta1;
    private javax.swing.JLabel imgCarta2;
    private javax.swing.JLabel imgCarta3;
    private javax.swing.JLabel imgCarta4;
    private javax.swing.JLabel imgCarta5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nombreJugador;
    private javax.swing.JLabel turno;
    // End of variables declaration
}
